claudeCode:
  enabled: true
  version: "latest"
  logLevel: info
  model: sonnet
  
  settings:
    alwaysThinkingEnabled: true
  
  mcpServers:
    - name: github
      type: sse
      url: "https://github-mcp-server.apps.tas-ndc.kuhn-labs.com/sse"

  skills:
    # Clone from git repository
    - name: limerick-skill
      git:
        url: https://github.com/cpage-pivotal/limerick-skill.git
        ref: main
